use northwind;
select ProductName,QuantityPerUnit from Products;
select ProductID,ProductName froml> desc Products;
select ProductID,ProductName,UnitPrice from Products where UnitPrice<20;
select ProductID,ProductName,UnitPrice from Products where UnitPrice=15 or UnitPrice=25;
select CategoryName, Description from Categories;
select ContactName, CompanyName, ContactTitle,Phone from Customers; 
select EmployeeID, Title, FirstName, LastName,Region from Employees;
select RegionID, RegionDescription from Region;
select CompanyName, Fax, Phone,HomePage from Suppliers;
select CategoryName,Description from Categories order by CategoryName;
select ContactName, CompanyName, ContactTitle, Phone from  Customers order by Phone;
select FirstName,LastName,HireDate from Employees order by HireDate  desc;
select OrderID,OrderDate,ShippedDate,CustomerID Freight from Orders order by Freight desc;
select CompanyName,Fax, Phone, HomePage,Country from Suppliers order by Country desc, CompanyName asc;
select Title,FirstName,LastName from Employees order by Title asc,LastName desc;
select CompanyName,ContactName from Customers where city='Buenos Aires';
select ProductName,UnitPrice,QuantityPerUnit from Products where UnitsInStock=0;
select OrderDate,ShippedDate,CustomerID,Freight from Orders where ShippedDate='1997-05-19';
select CompanyName,ContactName,Fax from Customers where Fax is not null;
select FirstName,LastName from Employees where ReportsTo is null or 0;
